name: Update Gist Twice Daily

on:
  schedule:
    - cron: '0 7 * * *' # 07:00 UTC --> circa 09:00 italiane
    - cron: '0 18 * * *' # 18:00 UTC --> circa 20:00 italiane
  workflow_dispatch: # Permette di avviarlo anche a mano

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the script
      env:
        GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: python update_gist.py
