name: Aggiorna Gist con news docenti

on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Esegui scraping news
        run: node newsDocenti.js

      - name: Aggiorna il Gist con le news
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          echo "Caricamento del file docenti-news.json su Gist..."
          node updateGist.js
