name: Update Gist with News

on:
  schedule:
    - cron: '0 9,18 * * *'  # Due volte al giorno: 9 AM e 6 PM
  workflow_dispatch:

jobs:
  update_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install  # Aggiungi questo per installare i browser Playwright

    - name: Run update_gist.py script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa il token GitHub predefinito
      run: python update_gist.py
